import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './layouts/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={inter.className}>
        <Navigation></Navigation>
        {children}
        
        </body>
    </html>
  )
}
